### ISSUE TITLE
How to determine whether KDE perform accurately for a given distribution using 1 marker?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [sistm/cytometree#12]
Hi there, 

Thank you for this useful tool! 

I want to determine the gate on 1-D (i.e., on a histogram of 1 channel only - CD4), so I ran `F37_sce_c14_cytometree <- cytometree::CytomeTree(t(assay(F37_sce_c14_cytometree)[c("CD4", "CD185"),]), minleaf = 1, t = 0.1, force_first_markers=c("CD4"))`

**Q1.** The code ran fine, but would you mind advising how we might determine whether we can trust the KDE's? And whether it is possible to also draw the normalised curve that actually show the final partition?

From FlowJo of the same cells: 

<img width="160" alt="Screenshot 2023-09-07 at 18 54 03" src="https://github.com/sistm/cytometree/assets/62179082/31b08738-e4ec-4586-bbb5-143f53438566">

Q2. With the code written as above, does that mean the partition of the cells is only determined using CD4 and not CD185? Even though I saw the tree (below) only shows splitting of CD4 and NAs are for the CD185 column, but wanted to make sure, because when I plotted `cytometree::Annotation`, I saw plots for both CD4 and CD185 (Gray-shaded plots)

<img width="721" alt="Screenshot 2023-09-07 at 18 28 13" src="https://github.com/sistm/cytometree/assets/62179082/26b1d15d-b891-4be5-8103-0698f0270986">

CD4: 
<img width="782" alt="Screenshot 2023-09-07 at 18 33 48" src="https://github.com/sistm/cytometree/assets/62179082/9db6ae27-938c-44b4-9636-7e0bb967521f">

CD185:
<img width="701" alt="Screenshot 2023-09-07 at 18 37 10" src="https://github.com/sistm/cytometree/assets/62179082/bdc8bcf4-fd65-4410-b152-a297493cef36">

<img width="243" alt="Screenshot 2023-09-07 at 18 37 56" src="https://github.com/sistm/cytometree/assets/62179082/c82515b1-df9b-46e2-aa28-96556a9ff807">

Thank you for your help!

**Comment by borishejblum** [comment]
Hi,

Thank you for your interest in `cytometree`.

**Q1.** The kernel density estimator does not look bi-modal on your data for CD4, as is also the case in log-scale according to your FlowJo screen capture. As the KDE is fully non-parametric, as long as you have enough, cells it is trustworthy. In your case, it does not look like you have two cell populations that are expressing different levels of CD4.

**Q2.** Your code only forces CD4 to be used for the first split but does not formally prevent CD185 to be used afterwards to split your cells into more populations. Yet, looking at your output for `$combinations` (with `NA`s in the CD185 column) , it was not used to further split the cells — likely because it did not meet the `t=0.1` threshold — hinting as your data having only one cell population homogeneous in CD185 once splitted in two according to CD4.
`cytometree::Annotation` will characterize each cell population identified for all markers, regardless of wether those markers are actually used or not to split the cells.

Best,
Boris
